# Generated by Django 4.1.5 on 2023-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_leaderboard_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAndQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('quiz_id', models.IntegerField()),
            ],
            options={
                'db_table': 'UserAndQuestion',
            },
        ),
    ]
