# Generated by Django 4.1.5 on 2023-01-25 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0005_userandquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandquestion',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.questionmodel'),
        ),
        migrations.AlterField(
            model_name='userandquestion',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz_category'),
        ),
        migrations.AlterField(
            model_name='userandquestion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
