# Generated by Django 4.1.5 on 2023-01-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_userandquestion_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='incorrect',
            field=models.FloatField(default=0),
        ),
    ]
